main: main.cpp buddy.cpp
	g++ main.cpp buddy.cpp -std=c++0x -o simulator

process_small: processGeneratorSmall.cpp
	g++ processGeneratorSmall.cpp -std=c++0x -o smallMemoryGenerator

process_medium: processGeneratorMedium.cpp
	g++ processGeneratorMedium.cpp -std=c++0x -o mediumMemoryGenerator

process_large: processGeneratorLarge.cpp
	g++ processGeneratorLarge.cpp -std=c++0x -o largeMemoryGenerator
